name: Primer workflow
on: push
jobs:
  ejercicio1:
    runs-on: ubuntu-latest

    steps:
      - name: Bajar codigo
        uses: actions/checkout@v4
        
      - name: Ejecutar codigo
        run: pip install pytest
        
      - name: Ejecutar codigo
        run: pytest test.py
